apiVersion: v1
kind: Service
metadata:
  name: ssh-mobile-backend
  labels:
    app: ssh-mobile-backend
spec:
  type: ClusterIP
  selector:
    app: ssh-mobile-backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    name: websocket
