apiVersion: v1
kind: Service
metadata:
  name: ssh-mobile-frontend
  labels:
    app: ssh-mobile-frontend
spec:
  type: ClusterIP
  selector:
    app: ssh-mobile-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
